# odp_rbh_to_groupby

rbh_file: analysis/odp_run/7_odp_rbh_to_hmm/odp_rbh_to_HMM/output/Cowczarzaki_Bmicroptera_Davara_Acrassa_Hpanicea_Abeatrix_Bcyanae_Sciliatum_Ccandelabrum_Olobularis_Nvectensis_rbhhmm_plus_other_species.rbh

num_permutations: 1000000
